package block

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"time"
)

// A block is represented by a struct with 4 attributes
type Block struct {
	timestamp    int64
	nonce        int
	previousHash [32]byte
	transactions []string
}

// NewBlock() takes nonce generated by performing POW and previousHash and creates a new block
func NewBlock(nonce int, previousHash [32]byte /*string*/) *Block {
	// new returns a pointer to a new Block strcut
	b := new(Block)
	b.timestamp = time.Now().UnixNano()
	b.nonce = nonce
	b.previousHash = previousHash
	return b
}

// Print the entire block
func (b *Block) PrintBlock() {
	fmt.Printf("timestamp      		 %d\n", b.timestamp)
	fmt.Printf("nonce          		 %d\n", b.nonce)
	fmt.Printf("previous_hash(HEXA)      %x\n", b.previousHash)
	fmt.Printf("transactions    	 %s\n", b.transactions)
}

// Custom marshaling function
func (b *Block) MarshalJSON() ([]byte, error) {
	return json.Marshal(struct {
		Timestamp    int64    `json:"timestamp"`
		Nonce        int      `json:"nonce"`
		PreviousHash [32]byte `json:"previous_hash"`
		Transactions []string `json:"transactions"`
	}{
		Timestamp:    b.timestamp,
		Nonce:        b.nonce,
		PreviousHash: b.previousHash,
		Transactions: b.transactions,
	})
}

// Hash a block and return a 256-bit output or 32 bytes
func (b *Block) Hash() [32]byte {
	m, err := json.Marshal(b)
	if err != nil {
		panic(err)
	}

	return sha256.Sum256(m)
}
